// ---------------------------------------------------------------------------
// MangaKick – In-memory database
// ---------------------------------------------------------------------------

// ========================  ANIME CHARACTERS  ================================
const animeCharacters = [
  // --- Blue Lock ---
  {
    id: "anime-1",
    name: "Yoichi Isagi",
    anime: "Blue Lock",
    image: "https://placehold.co/300x400?text=Isagi",
    position: "FWD",
    nationality: "Japan (Blue Lock)",
    stats: { pace: 78, shooting: 88, passing: 75, dribbling: 80, defense: 35, physical: 65 },
    specialAbility: { name: "Spatial Awareness", description: "Reads the entire field in a split second, finding the optimal position to score.", power: 8 },
    rarity: "epic",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "anime-2",
    name: "Meguru Bachira",
    anime: "Blue Lock",
    image: "https://placehold.co/300x400?text=Bachira",
    position: "MID",
    nationality: "Japan (Blue Lock)",
    stats: { pace: 85, shooting: 70, passing: 78, dribbling: 95, defense: 30, physical: 55 },
    specialAbility: { name: "Monster Dribble", description: "Unleashes his inner monster to perform unpredictable dribbles past any defender.", power: 9 },
    rarity: "epic",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "anime-3",
    name: "Rin Itoshi",
    anime: "Blue Lock",
    image: "https://placehold.co/300x400?text=Rin",
    position: "FWD",
    nationality: "Japan (Blue Lock)",
    stats: { pace: 82, shooting: 92, passing: 70, dribbling: 88, defense: 28, physical: 68 },
    specialAbility: { name: "Predator Eye", description: "Cold-blooded finishing instinct that activates under extreme pressure.", power: 9 },
    rarity: "legendary",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "anime-4",
    name: "Seishiro Nagi",
    anime: "Blue Lock",
    image: "https://placehold.co/300x400?text=Nagi",
    position: "FWD",
    nationality: "Japan (Blue Lock)",
    stats: { pace: 60, shooting: 85, passing: 65, dribbling: 90, defense: 25, physical: 55 },
    specialAbility: { name: "Trapping Genius", description: "Flawless first touch that turns any pass into a scoring chance.", power: 8 },
    rarity: "epic",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "anime-5",
    name: "Hyoma Chigiri",
    anime: "Blue Lock",
    image: "https://placehold.co/300x400?text=Chigiri",
    position: "FWD",
    nationality: "Japan (Blue Lock)",
    stats: { pace: 97, shooting: 75, passing: 68, dribbling: 82, defense: 30, physical: 50 },
    specialAbility: { name: "Lightning Sprint", description: "Explosive burst of speed that leaves defenders in the dust.", power: 8 },
    rarity: "epic",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },

  // --- Captain Tsubasa ---
  {
    id: "anime-6",
    name: "Tsubasa Ozora",
    anime: "Captain Tsubasa",
    image: "https://placehold.co/300x400?text=Tsubasa",
    position: "MID",
    nationality: "Japan (Nankatsu)",
    stats: { pace: 80, shooting: 90, passing: 92, dribbling: 93, defense: 45, physical: 65 },
    specialAbility: { name: "Drive Shot", description: "A powerful curving shot that bends mid-air and is nearly impossible to save.", power: 10 },
    rarity: "legendary",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "anime-7",
    name: "Kojiro Hyuga",
    anime: "Captain Tsubasa",
    image: "https://placehold.co/300x400?text=Hyuga",
    position: "FWD",
    nationality: "Japan (Toho)",
    stats: { pace: 78, shooting: 95, passing: 55, dribbling: 72, defense: 35, physical: 90 },
    specialAbility: { name: "Tiger Shot", description: "A devastatingly powerful shot fuelled by sheer willpower and raw strength.", power: 10 },
    rarity: "legendary",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "anime-8",
    name: "Genzo Wakabayashi",
    anime: "Captain Tsubasa",
    image: "https://placehold.co/300x400?text=Wakabayashi",
    position: "GK",
    nationality: "Japan (Nankatsu)",
    stats: { pace: 55, shooting: 20, passing: 60, dribbling: 35, defense: 95, physical: 88 },
    specialAbility: { name: "Super Great Guardian Keeper (SGGK)", description: "An almost supernatural ability to stop any shot no matter the power.", power: 10 },
    rarity: "legendary",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },

  // --- Inazuma Eleven ---
  {
    id: "anime-9",
    name: "Mamoru Endou",
    anime: "Inazuma Eleven",
    image: "https://placehold.co/300x400?text=Endou",
    position: "GK",
    nationality: "Japan (Raimon)",
    stats: { pace: 50, shooting: 30, passing: 65, dribbling: 40, defense: 92, physical: 80 },
    specialAbility: { name: "God Hand", description: "A divine catching technique that creates an enormous golden hand to stop any shot.", power: 9 },
    rarity: "epic",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "anime-10",
    name: "Shuuya Gouenji",
    anime: "Inazuma Eleven",
    image: "https://placehold.co/300x400?text=Gouenji",
    position: "FWD",
    nationality: "Japan (Raimon)",
    stats: { pace: 75, shooting: 93, passing: 60, dribbling: 70, defense: 30, physical: 75 },
    specialAbility: { name: "Fire Tornado", description: "A blazing spinning shot engulfed in flames that incinerates the net.", power: 9 },
    rarity: "epic",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },

  // --- Dragon Ball ---
  {
    id: "anime-11",
    name: "Goku",
    anime: "Dragon Ball",
    image: "https://placehold.co/300x400?text=Goku",
    position: "FWD",
    nationality: "Planet Vegeta",
    stats: { pace: 99, shooting: 90, passing: 65, dribbling: 85, defense: 60, physical: 99 },
    specialAbility: { name: "Kamehameha Kick", description: "Channels Ki energy into an unstoppable power shot that breaks the sound barrier.", power: 10 },
    rarity: "legendary",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "anime-12",
    name: "Vegeta",
    anime: "Dragon Ball",
    image: "https://placehold.co/300x400?text=Vegeta",
    position: "MID",
    nationality: "Planet Vegeta",
    stats: { pace: 95, shooting: 88, passing: 60, dribbling: 80, defense: 70, physical: 97 },
    specialAbility: { name: "Final Flash Volley", description: "A devastating volley charged with Saiyan pride energy.", power: 9 },
    rarity: "legendary",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },

  // --- Naruto ---
  {
    id: "anime-13",
    name: "Naruto Uzumaki",
    anime: "Naruto",
    image: "https://placehold.co/300x400?text=Naruto",
    position: "MID",
    nationality: "Konoha",
    stats: { pace: 90, shooting: 78, passing: 72, dribbling: 82, defense: 55, physical: 85 },
    specialAbility: { name: "Shadow Clone Overload", description: "Creates shadow clones that confuse defenders with multiple runs at once.", power: 9 },
    rarity: "legendary",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "anime-14",
    name: "Sasuke Uchiha",
    anime: "Naruto",
    image: "https://placehold.co/300x400?text=Sasuke",
    position: "FWD",
    nationality: "Konoha",
    stats: { pace: 92, shooting: 85, passing: 60, dribbling: 88, defense: 50, physical: 75 },
    specialAbility: { name: "Sharingan Vision", description: "Predicts goalkeeper movements with perfect accuracy before shooting.", power: 8 },
    rarity: "epic",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },

  // --- One Piece ---
  {
    id: "anime-15",
    name: "Monkey D. Luffy",
    anime: "One Piece",
    image: "https://placehold.co/300x400?text=Luffy",
    position: "FWD",
    nationality: "East Blue",
    stats: { pace: 85, shooting: 82, passing: 55, dribbling: 90, defense: 40, physical: 95 },
    specialAbility: { name: "Gomu Gomu no Shoot", description: "Stretches his leg impossibly far for a rubber-powered rocket shot.", power: 9 },
    rarity: "legendary",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "anime-16",
    name: "Roronoa Zoro",
    anime: "One Piece",
    image: "https://placehold.co/300x400?text=Zoro",
    position: "DEF",
    nationality: "East Blue",
    stats: { pace: 72, shooting: 55, passing: 50, dribbling: 60, defense: 95, physical: 97 },
    specialAbility: { name: "Three-Sword Tackle", description: "An intimidating defensive stance that terrifies any attacker into losing the ball.", power: 8 },
    rarity: "epic",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },

  // --- Haikyuu ---
  {
    id: "anime-17",
    name: "Shoyo Hinata",
    anime: "Haikyuu!!",
    image: "https://placehold.co/300x400?text=Hinata",
    position: "FWD",
    nationality: "Japan (Karasuno)",
    stats: { pace: 95, shooting: 80, passing: 70, dribbling: 75, defense: 40, physical: 60 },
    specialAbility: { name: "Super Quick Attack", description: "Incredible reflexes and jumping power for devastating headed goals.", power: 7 },
    rarity: "rare",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },

  // --- Kuroko no Basket ---
  {
    id: "anime-18",
    name: "Tetsuya Kuroko",
    anime: "Kuroko no Basket",
    image: "https://placehold.co/300x400?text=Kuroko",
    position: "MID",
    nationality: "Japan (Seirin)",
    stats: { pace: 60, shooting: 40, passing: 99, dribbling: 65, defense: 55, physical: 35 },
    specialAbility: { name: "Misdirection Pass", description: "Uses near-invisibility to deliver passes that defenders never see coming.", power: 9 },
    rarity: "epic",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "anime-19",
    name: "Taiga Kagami",
    anime: "Kuroko no Basket",
    image: "https://placehold.co/300x400?text=Kagami",
    position: "FWD",
    nationality: "Japan (Seirin)",
    stats: { pace: 88, shooting: 85, passing: 55, dribbling: 72, defense: 50, physical: 90 },
    specialAbility: { name: "Meteor Jam Header", description: "Leaps to impossible heights to head the ball with meteor-like force.", power: 8 },
    rarity: "epic",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },

  // --- Slam Dunk ---
  {
    id: "anime-20",
    name: "Hanamichi Sakuragi",
    anime: "Slam Dunk",
    image: "https://placehold.co/300x400?text=Sakuragi",
    position: "DEF",
    nationality: "Japan (Shohoku)",
    stats: { pace: 80, shooting: 65, passing: 55, dribbling: 50, defense: 88, physical: 95 },
    specialAbility: { name: "Tensai Rebound Clearance", description: "Self-proclaimed genius athleticism for winning every aerial duel.", power: 7 },
    rarity: "rare",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
];

// ========================  REAL FOOTBALLERS  ================================
const realFootballers = [
  {
    id: "real-1",
    name: "Lionel Messi",
    anime: null,
    image: "https://placehold.co/300x400?text=Messi",
    position: "FWD",
    nationality: "Argentina",
    stats: { pace: 81, shooting: 92, passing: 91, dribbling: 95, defense: 34, physical: 65 },
    specialAbility: { name: "La Pulga Dribble", description: "Mesmerising close-control dribble that glides past entire defences.", power: 10 },
    rarity: "legendary",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "real-2",
    name: "Cristiano Ronaldo",
    anime: null,
    image: "https://placehold.co/300x400?text=CR7",
    position: "FWD",
    nationality: "Portugal",
    stats: { pace: 84, shooting: 94, passing: 82, dribbling: 87, defense: 35, physical: 77 },
    specialAbility: { name: "Siuuu Power Shot", description: "A thunderous knuckleball free-kick followed by the iconic celebration.", power: 10 },
    rarity: "legendary",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "real-3",
    name: "Kylian Mbappé",
    anime: null,
    image: "https://placehold.co/300x400?text=Mbappe",
    position: "FWD",
    nationality: "France",
    stats: { pace: 97, shooting: 89, passing: 80, dribbling: 92, defense: 36, physical: 78 },
    specialAbility: { name: "Turbo Sprint", description: "Activates a gear of speed that no defender can match.", power: 9 },
    rarity: "legendary",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "real-4",
    name: "Erling Haaland",
    anime: null,
    image: "https://placehold.co/300x400?text=Haaland",
    position: "FWD",
    nationality: "Norway",
    stats: { pace: 89, shooting: 93, passing: 65, dribbling: 78, defense: 45, physical: 91 },
    specialAbility: { name: "Viking Smash", description: "An unstoppable power header/volley combining brute force with precision.", power: 9 },
    rarity: "legendary",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "real-5",
    name: "Vinícius Jr.",
    anime: null,
    image: "https://placehold.co/300x400?text=Vinicius",
    position: "FWD",
    nationality: "Brazil",
    stats: { pace: 95, shooting: 82, passing: 78, dribbling: 93, defense: 29, physical: 68 },
    specialAbility: { name: "Samba Stepovers", description: "Dazzling stepovers and feints that leave defenders dizzy.", power: 8 },
    rarity: "epic",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "real-6",
    name: "Jude Bellingham",
    anime: null,
    image: "https://placehold.co/300x400?text=Bellingham",
    position: "MID",
    nationality: "England",
    stats: { pace: 78, shooting: 82, passing: 83, dribbling: 84, defense: 72, physical: 82 },
    specialAbility: { name: "Box-to-Box Engine", description: "Relentless runs from defence to attack, arriving late to score crucial goals.", power: 8 },
    rarity: "epic",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "real-7",
    name: "Pedri",
    anime: null,
    image: "https://placehold.co/300x400?text=Pedri",
    position: "MID",
    nationality: "Spain",
    stats: { pace: 72, shooting: 68, passing: 90, dribbling: 88, defense: 65, physical: 62 },
    specialAbility: { name: "Canarian Maestro", description: "Elegant ball retention and vision that controls the tempo of the entire match.", power: 8 },
    rarity: "epic",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "real-8",
    name: "Gavi",
    anime: null,
    image: "https://placehold.co/300x400?text=Gavi",
    position: "MID",
    nationality: "Spain",
    stats: { pace: 78, shooting: 65, passing: 82, dribbling: 82, defense: 72, physical: 75 },
    specialAbility: { name: "Fiery Tenacity", description: "Aggressive pressing and fearless tackles despite his small frame.", power: 7 },
    rarity: "rare",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "real-9",
    name: "Luka Modrić",
    anime: null,
    image: "https://placehold.co/300x400?text=Modric",
    position: "MID",
    nationality: "Croatia",
    stats: { pace: 72, shooting: 76, passing: 93, dribbling: 90, defense: 68, physical: 60 },
    specialAbility: { name: "Balkan Maestro", description: "A magical outside-foot pass that unlocks any defence.", power: 9 },
    rarity: "legendary",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "real-10",
    name: "Toni Kroos",
    anime: null,
    image: "https://placehold.co/300x400?text=Kroos",
    position: "MID",
    nationality: "Germany",
    stats: { pace: 55, shooting: 80, passing: 95, dribbling: 82, defense: 70, physical: 68 },
    specialAbility: { name: "Surgical Pass", description: "Pinpoint 40-yard passes delivered with metronomic consistency.", power: 9 },
    rarity: "legendary",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "real-11",
    name: "Mohamed Salah",
    anime: null,
    image: "https://placehold.co/300x400?text=Salah",
    position: "FWD",
    nationality: "Egypt",
    stats: { pace: 93, shooting: 87, passing: 79, dribbling: 90, defense: 45, physical: 75 },
    specialAbility: { name: "Egyptian King Cut-Inside", description: "Signature cut from the right wing onto his lethal left foot.", power: 8 },
    rarity: "epic",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "real-12",
    name: "Kevin De Bruyne",
    anime: null,
    image: "https://placehold.co/300x400?text=KDB",
    position: "MID",
    nationality: "Belgium",
    stats: { pace: 74, shooting: 86, passing: 95, dribbling: 87, defense: 60, physical: 78 },
    specialAbility: { name: "Laser Through-Ball", description: "Perfectly weighted through-balls with impossible precision.", power: 9 },
    rarity: "legendary",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "real-13",
    name: "Robert Lewandowski",
    anime: null,
    image: "https://placehold.co/300x400?text=Lewandowski",
    position: "FWD",
    nationality: "Poland",
    stats: { pace: 72, shooting: 95, passing: 78, dribbling: 85, defense: 44, physical: 82 },
    specialAbility: { name: "Clinical Finisher", description: "Converts half-chances into goals with machine-like precision.", power: 9 },
    rarity: "legendary",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "real-14",
    name: "Neymar Jr.",
    anime: null,
    image: "https://placehold.co/300x400?text=Neymar",
    position: "FWD",
    nationality: "Brazil",
    stats: { pace: 87, shooting: 83, passing: 86, dribbling: 94, defense: 30, physical: 58 },
    specialAbility: { name: "Joga Bonito Rainbow", description: "A rainbow flick followed by a spectacular skill combo.", power: 9 },
    rarity: "legendary",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "real-15",
    name: "Karim Benzema",
    anime: null,
    image: "https://placehold.co/300x400?text=Benzema",
    position: "FWD",
    nationality: "France",
    stats: { pace: 76, shooting: 90, passing: 83, dribbling: 88, defense: 39, physical: 78 },
    specialAbility: { name: "Cat Reflex Finish", description: "Instinctive poacher's finish from the most impossible angles.", power: 9 },
    rarity: "legendary",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "real-16",
    name: "Thibaut Courtois",
    anime: null,
    image: "https://placehold.co/300x400?text=Courtois",
    position: "GK",
    nationality: "Belgium",
    stats: { pace: 45, shooting: 15, passing: 55, dribbling: 25, defense: 92, physical: 85 },
    specialAbility: { name: "Wall of Madrid", description: "Becomes an impenetrable wall in big-game moments, denying everything.", power: 9 },
    rarity: "epic",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "real-17",
    name: "Gianluigi Donnarumma",
    anime: null,
    image: "https://placehold.co/300x400?text=Donnarumma",
    position: "GK",
    nationality: "Italy",
    stats: { pace: 48, shooting: 12, passing: 58, dribbling: 22, defense: 90, physical: 88 },
    specialAbility: { name: "Giant's Reach", description: "Enormous wingspan covers every inch of the goal for remarkable saves.", power: 8 },
    rarity: "epic",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "real-18",
    name: "Sergio Ramos",
    anime: null,
    image: "https://placehold.co/300x400?text=Ramos",
    position: "DEF",
    nationality: "Spain",
    stats: { pace: 70, shooting: 60, passing: 65, dribbling: 55, defense: 93, physical: 90 },
    specialAbility: { name: "Captain's Header", description: "Scores crucial last-minute headers in the biggest matches.", power: 9 },
    rarity: "legendary",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "real-19",
    name: "Virgil van Dijk",
    anime: null,
    image: "https://placehold.co/300x400?text=VanDijk",
    position: "DEF",
    nationality: "Netherlands",
    stats: { pace: 75, shooting: 55, passing: 72, dribbling: 60, defense: 95, physical: 92 },
    specialAbility: { name: "Colossus Block", description: "An imposing physical presence that makes attackers doubt themselves.", power: 9 },
    rarity: "legendary",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
  {
    id: "real-20",
    name: "Lamine Yamal",
    anime: null,
    image: "https://placehold.co/300x400?text=Yamal",
    position: "FWD",
    nationality: "Spain",
    stats: { pace: 90, shooting: 78, passing: 82, dribbling: 89, defense: 28, physical: 58 },
    specialAbility: { name: "Wonderkid Vision", description: "Sees passes and spaces beyond his years, creating magic from nothing.", power: 8 },
    rarity: "epic",
    level: 1,
    xp: 0,
    maxLevel: 10,
  },
];

// ========================  TRAINING DRILLS  =================================
const trainingDrills = [
  {
    id: "drill-1",
    name: "Sprint Training",
    description: "High-intensity sprint drills to increase explosive speed and acceleration.",
    xpReward: 30,
    statBoost: { stat: "pace", amount: 2 },
    duration: 15,
    cost: 50,
  },
  {
    id: "drill-2",
    name: "Target Practice",
    description: "Precision shooting at designated targets from various angles and distances.",
    xpReward: 35,
    statBoost: { stat: "shooting", amount: 2 },
    duration: 20,
    cost: 60,
  },
  {
    id: "drill-3",
    name: "Passing Drills",
    description: "Short and long-range passing exercises with moving targets.",
    xpReward: 25,
    statBoost: { stat: "passing", amount: 2 },
    duration: 15,
    cost: 40,
  },
  {
    id: "drill-4",
    name: "Dribbling Course",
    description: "Navigate through a complex cone course to sharpen close ball-control.",
    xpReward: 35,
    statBoost: { stat: "dribbling", amount: 2 },
    duration: 20,
    cost: 55,
  },
  {
    id: "drill-5",
    name: "Defense Tactics",
    description: "Positional drills and 1v1 defending scenarios against attackers.",
    xpReward: 30,
    statBoost: { stat: "defense", amount: 2 },
    duration: 20,
    cost: 50,
  },
  {
    id: "drill-6",
    name: "Gym Workout",
    description: "Strength and conditioning session to build power and endurance.",
    xpReward: 30,
    statBoost: { stat: "physical", amount: 2 },
    duration: 25,
    cost: 45,
  },
  {
    id: "drill-7",
    name: "Special Move Training",
    description: "Practise your character's signature special ability to perfection.",
    xpReward: 50,
    statBoost: { stat: "shooting", amount: 3 },
    duration: 30,
    cost: 100,
  },
  {
    id: "drill-8",
    name: "Team Chemistry",
    description: "Small-sided games to build understanding and coordination with teammates.",
    xpReward: 40,
    statBoost: { stat: "passing", amount: 3 },
    duration: 25,
    cost: 70,
  },
  {
    id: "drill-9",
    name: "Mental Focus",
    description: "Visualisation and concentration exercises for clutch-moment composure.",
    xpReward: 20,
    statBoost: { stat: "dribbling", amount: 1 },
    duration: 10,
    cost: 30,
  },
  {
    id: "drill-10",
    name: "Recovery Session",
    description: "Light stretching and recovery work to prevent injuries and restore energy.",
    xpReward: 15,
    statBoost: { stat: "physical", amount: 1 },
    duration: 10,
    cost: 20,
  },
];

// ========================  HELPER FUNCTIONS  ================================

/**
 * Calculate the overall rating as the average of all six stats.
 */
export function calculateOverall(stats) {
  const { pace, shooting, passing, dribbling, defense, physical } = stats;
  return Math.round((pace + shooting + passing + dribbling + defense + physical) / 6);
}

/**
 * Find a player by ID across both arrays.
 */
export function getPlayerById(id) {
  return (
    animeCharacters.find((p) => p.id === id) ||
    realFootballers.find((p) => p.id === id) ||
    null
  );
}

/**
 * Return a combined array of all players.
 */
export function getAllPlayers() {
  return [...animeCharacters, ...realFootballers];
}

// ========================  DEFAULT EXPORT  ==================================
const db = {
  animeCharacters,
  realFootballers,
  trainingDrills,
};

export default db;
